### ISSUE TITLE
Cursor cannot display 

### ISSUE THREAD

**Issue by X-G** [lexicalunit/multi-wrap-guide#12] opened 2015-06-19 07:50 UTC
I found that if the cursor is in the same column with the wrap guide, the cursor wound be in the behind of the wrap guide and cannot be seen.

**Comment by lexicalunit** [comment] 2015-06-19 15:30
Interesting, this is what I am seeing:

![out](https://cloud.githubusercontent.com/assets/1903876/8256631/fde8ff5e-166d-11e5-8651-26859434bc42.gif)
- Do you have packages or customizations installed that affect the cursor?
- Also what syntax theme are you using? I'll install it too and see if that could be causing the issue.
- And what UI theme are you using?

**Comment by lexicalunit** [comment] 2015-06-20 19:18
I am able to reproduce this if I set the color of the wrap guide to be white (or whatever the color of the cursor happens to be):

![screen shot 2015-06-20 at 2 00 17 pm](https://cloud.githubusercontent.com/assets/1903876/8268765/b601cd14-1754-11e5-9f87-9ddabaf8e433.png)
Here the cursor is directly after the `d` in `background-color` but you can't see it because the guide and the cursor are the same color.

The solution in this case would be to lower the opacity of the guide:

![screen shot 2015-06-20 at 2 01 58 pm](https://cloud.githubusercontent.com/assets/1903876/8268775/f0729c44-1754-11e5-9370-1c4530cc2cba.png)

Or change the color of the cursor:

![screen shot 2015-06-20 at 2 04 14 pm](https://cloud.githubusercontent.com/assets/1903876/8268814/4173728a-1755-11e5-908d-9b945d57bfc9.png)

However, I noticed when I changed the color of the cursor, it would still not be visible without also changing its z-index. This is because by default the cursor's z-index is `auto` and the wrap guides have explicit 100+ z-index values. I'm going to fix this z-indexing issue in my next commit.

**Comment by lexicalunit** [comment] 2015-06-20 19:20
Resolved in commit 0c3056d16bec2ccc0a7678462303ed942cbf4943.

**Closed as completed by lexicalunit** 2015-06-20 19:20 UTC

**Comment by X-G** [comment] 2015-06-20 21:21
sorry for my late raply.
The problem seems been solved.
Thanks for your work on this package.
